coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
      formulation_bench:
        target: auto
        threshold: 1%
        flags:
          - formulation_bench
      milp_flare:
        target: auto
        threshold: 1%
        flags:
          - milp_flare
      src:
        target: auto
        threshold: 1%
        flags:
          - src
    patch:
      default:
        target: auto

flags:
  formulation_bench:
    paths:
      - packages/formulation_bench/src/formulation_bench
    carryforward: true
  milp_flare:
    paths:
      - packages/milp_flare/src/milp_flare
    carryforward: true
  src:
    paths:
      - src
    carryforward: true

comment:
  layout: "header, diff, flags, components, files"
  require_changes: false
