name = "flare"
version = "0.1.0"
defaultTargets = []

[[require]]
name = "FormulationBench"
git = "https://github.com/henryrobbins/formulation-bench"
subDir = "dataset"
rev = "main"

[[lean_lib]]
name = "Results"
srcDir = "."
globs = ["results.+"]
