#!/usr/bin/env bash

set -uo pipefail

# The agent working directory on the host is bind mounted to /workspace/wd
WD=/workspace/wd
AGENT_SH=$WD/agent.sh
COMPILE_LOG=$WD/compile_log.txt
RESULT=$WD/result.json

# Verify the agent working directory has the `agent.sh` with agent invocation
# command and `prompt.txt` with the agent prompt to pass to the agent CLIs.
if [[ ! -f $AGENT_SH ]]; then
    echo "entrypoint: missing $AGENT_SH" >&2
    exit 2
fi
if [[ ! -f $WD/prompt.txt ]]; then
    echo "entrypoint: missing $WD/prompt.txt" >&2
    exit 2
fi

# Symlink the image-baked .lake with pre-fetched mathlib oleans into the agent
# working directory so it's available to the agent, but the build artifacts are
# confined to the container and don't pollute the host.
ln -sfn /workspace/.lake "$WD/.lake"

# Run the agent command
cd "$WD"
# Initialize $PROMPT for use in agent command scripts
# See src/verify/flare/harness/agent_commands/*.sh for usage
export PROMPT="$(cat "$WD/prompt.txt")"
bash "$AGENT_SH"
AGENT_EXIT=$?

: > "$COMPILE_LOG"

run_compile() {
    local file="$1"
    echo "=== $file ===" >> "$COMPILE_LOG"
    lake env lean "$file" >> "$COMPILE_LOG" 2>&1
    local rc=$?
    echo "=== exit: $rc ===" >> "$COMPILE_LOG"
    return $rc
}

# Compile the three key files generated by the agent
run_compile A/Formulation.lean; FORM_A_EXIT=$?
run_compile B/Formulation.lean; FORM_B_EXIT=$?
run_compile Reformulation.lean; COMPILE_EXIT=$?

# Construct result JSON with agent exit code and compile exit codes
cat > "$RESULT" <<EOF
{"agent_exit": $AGENT_EXIT, "form_a_compile_exit": $FORM_A_EXIT, "form_b_compile_exit": $FORM_B_EXIT, "compile_exit": $COMPILE_EXIT}
EOF

exit $COMPILE_EXIT
