#!/usr/bin/env bash

set -uo pipefail

# The agent working directory on the host is bind mounted to /workspace/wd
WD=/workspace/wd
AGENT_SH=$WD/agent.sh
COMPILE_LOG=$WD/compile_log.txt
RESULT=$WD/result.json

# Verify the agent working directory has the `agent.sh` with agent invocation
# command and `prompt.txt` with the agent prompt to pass to the agent CLIs.
if [[ ! -f $AGENT_SH ]]; then
    echo "entrypoint: missing $AGENT_SH" >&2
    exit 2
fi
if [[ ! -f $WD/prompt.txt ]]; then
    echo "entrypoint: missing $WD/prompt.txt" >&2
    exit 2
fi

# Symlink the image-baked .lake with pre-fetched mathlib oleans into the agent
# working directory so it's available to the agent, but the build artifacts are
# confined to the container and don't pollute the host.
ln -sfn /workspace/.lake "$WD/.lake"

# Run the agent command
cd "$WD"
# Initialize $PROMPT for use in agent command scripts
# See milp_flare/assets/scripts/*.sh for usage
export PROMPT="$(cat "$WD/prompt.txt")"
bash "$AGENT_SH"
AGENT_EXIT=$?

: > "$COMPILE_LOG"

run_compile() {
    local file="$1"
    echo "=== $file ===" >> "$COMPILE_LOG"
    lake env lean "$file" >> "$COMPILE_LOG" 2>&1
    local rc=$?
    echo "=== exit: $rc ===" >> "$COMPILE_LOG"
    return $rc
}

# Compile the formulation files generated by the agent
run_compile A/Formulation.lean; FORM_A_EXIT=$?
run_compile B/Formulation.lean; FORM_B_EXIT=$?

# Compile the reformulation proof. If it declares a `MILPReformulation` def,
# compile a copy with `#print axioms <def>` appended so the host can detect
# any axioms the proof depends on beyond Lean's standard set. The command is
# inserted before the file's final `end` so the unqualified def name resolves
# inside its namespace.
#
# Newlines are flattened to spaces before matching so a signature split across
# lines (e.g. `def foo :` on one line, `MILPReformulation ... where` on the
# next) is still detected; the line-based grep would otherwise miss it.
REFORM_DEF=$(tr '\n' ' ' < Reformulation.lean 2>/dev/null \
    | grep -oE 'def[[:space:]]+[A-Za-z0-9_]+[[:space:]]*:[[:space:]]*MILPReformulation' \
    | head -1 | sed -E 's/.*def[[:space:]]+([A-Za-z0-9_]+).*/\1/')
if [[ -n $REFORM_DEF ]]; then
    awk -v cmd="#print axioms ${REFORM_DEF}" '
        { lines[NR] = $0; if ($0 ~ /^end([ \t]|$)/) last = NR }
        END {
            for (i = 1; i <= NR; i++) {
                if (i == last) print cmd
                print lines[i]
            }
            if (last == 0) print cmd
        }
    ' Reformulation.lean > _AxiomCheck.lean
    run_compile _AxiomCheck.lean; COMPILE_EXIT=$?
else
    run_compile Reformulation.lean; COMPILE_EXIT=$?
fi

# Construct result JSON with agent exit code and compile exit codes
cat > "$RESULT" <<EOF
{"agent_exit": $AGENT_EXIT, "form_a_compile_exit": $FORM_A_EXIT, "form_b_compile_exit": $FORM_B_EXIT, "compile_exit": $COMPILE_EXIT}
EOF

exit $COMPILE_EXIT
